name: update gist

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5be83d2a6d61e5c409fbae7923c85a2b
          USERNAME: vouxx
